### ISSUE TITLE
Sir, How are you so Machaxx :O

### ISSUE THREAD

**Issue by AjitPant** [r-khanna/PassGAN-A-deep-learning-approach-for-password-guessing#1]

**Comment by r-khanna** [comment]
This is very unprofessinal Mr. Ajit. Please refrain from such comments in the future. @AjitPant

**Comment by AjitPant** [comment]
Sorry sir I am a not as machau as you, hence this mistake. Kindly forgive this lesser being. @r-khanna

**Comment by r-khanna** [comment]
@AjitPant , I am sorry to inform you but we have decided to set up an internal review committee to review your misconduct. This is a serious offence and we may have to seek legal action against it too. You are advised to be prepared with a lawyer.
@Sawarnik123 please initiate the proceedings against Mr. Ajit. 
@ritvikjain99 please provide your input into the matter.

**Comment by AjitPant** [comment]
@r-khanna  This issue seems to have escalated out of control and hence could not be supressed any longer, hence reopening this.

**Comment by r-khanna** [comment]
> 
> 
> @r-khanna This issue seems to have escalated out of control and hence could not be supressed any longer, hence reopening this.

SO BE IT !

**Comment by Sawarnik123** [comment]
![f8d92ecb-3034-4d09-bfa7-5bbdf909519f](https://user-images.githubusercontent.com/44167344/100205620-5d478700-2f2b-11eb-9279-527cd813fe98.jpg)

**Comment by r-khanna** [comment]
> 
> 
> ![f8d92ecb-3034-4d09-bfa7-5bbdf909519f](https://user-images.githubusercontent.com/44167344/100205620-5d478700-2f2b-11eb-9279-527cd813fe98.jpg)

This is great!
@Sawarnik123 I trusted you to make an informed decision on Mr. Ajit's misconduct but now you yourself are indulging in such malpractices. This is completely unacceptable!!!
Please show professionalism. Else, God help me but I will have to take some action against you too.
